name: reMBCP

on:
  workflow_dispatch:
    inputs:
      input_url:
        description: 'Link to newest MB app'
        required: true

jobs:
  Build_Status:
    runs-on: ubuntu-latest
    steps:
      - name: Clean All Junk,App
        run: |
          docker rmi `docker images -q` || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d || true
          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* || true
          sudo apt -y autoremove --purge || true
          sudo apt -y autoclean || true
          sudo apt clean || true

      - name: Checkout code
        uses: actions/checkout@main

      - name: Checkout WORKSPACE
        run: |
          
          git clone -b minimal https://${{ secrets.rembcp }}@github.com/reMBCP/Rembbpatch.git

      - name: Set up Time
        run: |
          echo "Setting Vienam timezone"
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh

      - name: Install Stuff
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 curl wget python3 libgtk-3-dev aapt busybox zip unzip p7zip-full zipalign zstd bc xmlstarlet
          
          
      - name: Install OpenJDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: CHMOD
        run: |
          cd Rembbpatch/MBCPApp
          sudo chmod 777 -R *

      - name: Patching
        env:
          INPUT_URL: ${{ inputs.input_url }}
        run: |
          cd Rembbpatch/MBCPApp
          sudo bash autopatch.sh "$INPUT_URL"
      
